/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq;


import com.steeplesoft.simplesec.app.model.jooq.tables.FlywaySchemaHistory;
import com.steeplesoft.simplesec.app.model.jooq.tables.UserAccount;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_TENANT_ID = Internal.createIndex(DSL.name("idx_tenant_id"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.TENANT_ID, UserAccount.USER_ACCOUNT.ID }, false);
    public static final Index IDX_USER_NAME = Internal.createIndex(DSL.name("idx_user_name"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.USER_NAME }, false);
}
