/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq;


import com.steeplesoft.simplesec.app.model.jooq.tables.FlywaySchemaHistory;
import com.steeplesoft.simplesec.app.model.jooq.tables.JwtMetadata;
import com.steeplesoft.simplesec.app.model.jooq.tables.PasswordRecovery;
import com.steeplesoft.simplesec.app.model.jooq.tables.UserAccount;

import jakarta.annotation.Nonnull;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.jwt_metadata</code>.
     */
    public final JwtMetadata JWT_METADATA = JwtMetadata.JWT_METADATA;

    /**
     * The table <code>public.password_recovery</code>.
     */
    public final PasswordRecovery PASSWORD_RECOVERY = PasswordRecovery.PASSWORD_RECOVERY;

    /**
     * The table <code>public.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    @Nonnull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @Nonnull
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.PASSWORD_RECOVERY_SEQ,
            Sequences.USER_ACCOUNT_SEQ
        );
    }

    @Override
    @Nonnull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            JwtMetadata.JWT_METADATA,
            PasswordRecovery.PASSWORD_RECOVERY,
            UserAccount.USER_ACCOUNT
        );
    }
}
