/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.password_recovery_seq</code>
     */
    public static final Sequence<Long> PASSWORD_RECOVERY_SEQ = Internal.createSequence("password_recovery_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.user_account_seq</code>
     */
    public static final Sequence<Long> USER_ACCOUNT_SEQ = Internal.createSequence("user_account_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
