/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.smij.app.model.jooq.tables;


import com.steeplesoft.smij.app.model.jooq.Keys;
import com.steeplesoft.smij.app.model.jooq.Public;
import com.steeplesoft.smij.app.model.jooq.tables.records.PasswordRecoveryRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.time.OffsetDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordRecovery extends TableImpl<PasswordRecoveryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.password_recovery</code>
     */
    public static final PasswordRecovery PASSWORD_RECOVERY = new PasswordRecovery();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<PasswordRecoveryRecord> getRecordType() {
        return PasswordRecoveryRecord.class;
    }

    /**
     * The column <code>public.password_recovery.id</code>.
     */
    public final TableField<PasswordRecoveryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.password_recovery.user_name</code>.
     */
    public final TableField<PasswordRecoveryRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.VARCHAR(320), this, "");

    /**
     * The column <code>public.password_recovery.recovery_token</code>.
     */
    public final TableField<PasswordRecoveryRecord, String> RECOVERY_TOKEN = createField(DSL.name("recovery_token"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>public.password_recovery.expiry_date</code>.
     */
    public final TableField<PasswordRecoveryRecord, OffsetDateTime> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private PasswordRecovery(Name alias, Table<PasswordRecoveryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PasswordRecovery(Name alias, Table<PasswordRecoveryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.password_recovery</code> table reference
     */
    public PasswordRecovery(String alias) {
        this(DSL.name(alias), PASSWORD_RECOVERY);
    }

    /**
     * Create an aliased <code>public.password_recovery</code> table reference
     */
    public PasswordRecovery(Name alias) {
        this(alias, PASSWORD_RECOVERY);
    }

    /**
     * Create a <code>public.password_recovery</code> table reference
     */
    public PasswordRecovery() {
        this(DSL.name("password_recovery"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Identity<PasswordRecoveryRecord, Long> getIdentity() {
        return (Identity<PasswordRecoveryRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public UniqueKey<PasswordRecoveryRecord> getPrimaryKey() {
        return Keys.PASSWORD_RECOVERY_PKEY;
    }

    @Override
    @Nonnull
    public PasswordRecovery as(String alias) {
        return new PasswordRecovery(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public PasswordRecovery as(Name alias) {
        return new PasswordRecovery(alias, this);
    }

    @Override
    @Nonnull
    public PasswordRecovery as(Table<?> alias) {
        return new PasswordRecovery(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public PasswordRecovery rename(String name) {
        return new PasswordRecovery(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public PasswordRecovery rename(Name name) {
        return new PasswordRecovery(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public PasswordRecovery rename(Table<?> name) {
        return new PasswordRecovery(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery where(Condition condition) {
        return new PasswordRecovery(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public PasswordRecovery where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public PasswordRecovery where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public PasswordRecovery where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public PasswordRecovery where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public PasswordRecovery whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
