/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.records;


import com.steeplesoft.simplesec.app.model.jooq.tables.FlywaySchemaHistory;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistoryRecord extends UpdatableRecordImpl<FlywaySchemaHistoryRecord> implements Record10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledRank(@Nonnull Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    @NotNull
    @Nonnull
    public Integer getInstalledRank() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.flyway_schema_history.version</code>.
     */
    public FlywaySchemaHistoryRecord setVersion(@Nullable String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.version</code>.
     */
    @Size(max = 50)
    @Nullable
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.flyway_schema_history.description</code>.
     */
    public FlywaySchemaHistoryRecord setDescription(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.description</code>.
     */
    @NotNull
    @Size(max = 200)
    @Nonnull
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.flyway_schema_history.type</code>.
     */
    public FlywaySchemaHistoryRecord setType(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.type</code>.
     */
    @NotNull
    @Size(max = 20)
    @Nonnull
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.flyway_schema_history.script</code>.
     */
    public FlywaySchemaHistoryRecord setScript(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.script</code>.
     */
    @NotNull
    @Size(max = 1000)
    @Nonnull
    public String getScript() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.flyway_schema_history.checksum</code>.
     */
    public FlywaySchemaHistoryRecord setChecksum(@Nullable Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.checksum</code>.
     */
    @Nullable
    public Integer getChecksum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.flyway_schema_history.installed_by</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledBy(@Nonnull String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_by</code>.
     */
    @NotNull
    @Size(max = 100)
    @Nonnull
    public String getInstalledBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.flyway_schema_history.installed_on</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledOn(@Nullable LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_on</code>.
     */
    @Nullable
    public LocalDateTime getInstalledOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.flyway_schema_history.execution_time</code>.
     */
    public FlywaySchemaHistoryRecord setExecutionTime(@Nonnull Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.execution_time</code>.
     */
    @NotNull
    @Nonnull
    public Integer getExecutionTime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.flyway_schema_history.success</code>.
     */
    public FlywaySchemaHistoryRecord setSuccess(@Nonnull Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.success</code>.
     */
    @NotNull
    @Nonnull
    public Boolean getSuccess() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row10<Integer, String, String, String, String, Integer, String, LocalDateTime, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Integer> field1() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK;
    }

    @Override
    @Nonnull
    public Field<String> field2() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.VERSION;
    }

    @Override
    @Nonnull
    public Field<String> field3() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.DESCRIPTION;
    }

    @Override
    @Nonnull
    public Field<String> field4() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.TYPE;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SCRIPT;
    }

    @Override
    @Nonnull
    public Field<Integer> field6() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.CHECKSUM;
    }

    @Override
    @Nonnull
    public Field<String> field7() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY;
    }

    @Override
    @Nonnull
    public Field<LocalDateTime> field8() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON;
    }

    @Override
    @Nonnull
    public Field<Integer> field9() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME;
    }

    @Override
    @Nonnull
    public Field<Boolean> field10() {
        return FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS;
    }

    @Override
    @Nonnull
    public Integer component1() {
        return getInstalledRank();
    }

    @Override
    @Nullable
    public String component2() {
        return getVersion();
    }

    @Override
    @Nonnull
    public String component3() {
        return getDescription();
    }

    @Override
    @Nonnull
    public String component4() {
        return getType();
    }

    @Override
    @Nonnull
    public String component5() {
        return getScript();
    }

    @Override
    @Nullable
    public Integer component6() {
        return getChecksum();
    }

    @Override
    @Nonnull
    public String component7() {
        return getInstalledBy();
    }

    @Override
    @Nullable
    public LocalDateTime component8() {
        return getInstalledOn();
    }

    @Override
    @Nonnull
    public Integer component9() {
        return getExecutionTime();
    }

    @Override
    @Nonnull
    public Boolean component10() {
        return getSuccess();
    }

    @Override
    @Nonnull
    public Integer value1() {
        return getInstalledRank();
    }

    @Override
    @Nullable
    public String value2() {
        return getVersion();
    }

    @Override
    @Nonnull
    public String value3() {
        return getDescription();
    }

    @Override
    @Nonnull
    public String value4() {
        return getType();
    }

    @Override
    @Nonnull
    public String value5() {
        return getScript();
    }

    @Override
    @Nullable
    public Integer value6() {
        return getChecksum();
    }

    @Override
    @Nonnull
    public String value7() {
        return getInstalledBy();
    }

    @Override
    @Nullable
    public LocalDateTime value8() {
        return getInstalledOn();
    }

    @Override
    @Nonnull
    public Integer value9() {
        return getExecutionTime();
    }

    @Override
    @Nonnull
    public Boolean value10() {
        return getSuccess();
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value1(@Nonnull Integer value) {
        setInstalledRank(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value2(@Nullable String value) {
        setVersion(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value3(@Nonnull String value) {
        setDescription(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value4(@Nonnull String value) {
        setType(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value5(@Nonnull String value) {
        setScript(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value6(@Nullable Integer value) {
        setChecksum(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value7(@Nonnull String value) {
        setInstalledBy(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value8(@Nullable LocalDateTime value) {
        setInstalledOn(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value9(@Nonnull Integer value) {
        setExecutionTime(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord value10(@Nonnull Boolean value) {
        setSuccess(value);
        return this;
    }

    @Override
    @Nonnull
    public FlywaySchemaHistoryRecord values(@Nonnull Integer value1, @Nullable String value2, @Nonnull String value3, @Nonnull String value4, @Nonnull String value5, @Nullable Integer value6, @Nonnull String value7, @Nullable LocalDateTime value8, @Nonnull Integer value9, @Nonnull Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord() {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord(@Nonnull Integer installedRank, @Nullable String version, @Nonnull String description, @Nonnull String type, @Nonnull String script, @Nullable Integer checksum, @Nonnull String installedBy, @Nullable LocalDateTime installedOn, @Nonnull Integer executionTime, @Nonnull Boolean success) {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);

        setInstalledRank(installedRank);
        setVersion(version);
        setDescription(description);
        setType(type);
        setScript(script);
        setChecksum(checksum);
        setInstalledBy(installedBy);
        setInstalledOn(installedOn);
        setExecutionTime(executionTime);
        setSuccess(success);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord(com.steeplesoft.simplesec.app.model.jooq.tables.pojos.FlywaySchemaHistory value) {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);

        if (value != null) {
            setInstalledRank(value.getInstalledRank());
            setVersion(value.getVersion());
            setDescription(value.getDescription());
            setType(value.getType());
            setScript(value.getScript());
            setChecksum(value.getChecksum());
            setInstalledBy(value.getInstalledBy());
            setInstalledOn(value.getInstalledOn());
            setExecutionTime(value.getExecutionTime());
            setSuccess(value.getSuccess());
            resetChangedOnNotNull();
        }
    }
}
