/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.records;


import com.steeplesoft.simplesec.app.model.jooq.tables.JwtMetadata;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JwtMetadataRecord extends UpdatableRecordImpl<JwtMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.jwt_metadata.id</code>.
     */
    public JwtMetadataRecord setId(@Nonnull String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.id</code>.
     */
    @NotNull
    @Nonnull
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.jwt_metadata.user_name</code>.
     */
    public JwtMetadataRecord setUserName(@Nullable String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.user_name</code>.
     */
    @Size(max = 320)
    @Nullable
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.jwt_metadata.expiry_date</code>.
     */
    public JwtMetadataRecord setExpiryDate(@Nullable OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.expiry_date</code>.
     */
    @Nullable
    public OffsetDateTime getExpiryDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.jwt_metadata.revoked</code>.
     */
    public JwtMetadataRecord setRevoked(@Nullable Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.revoked</code>.
     */
    @Nullable
    public Boolean getRevoked() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JwtMetadataRecord
     */
    public JwtMetadataRecord() {
        super(JwtMetadata.JWT_METADATA);
    }

    /**
     * Create a detached, initialised JwtMetadataRecord
     */
    public JwtMetadataRecord(@Nonnull String id, @Nullable String userName, @Nullable OffsetDateTime expiryDate, @Nullable Boolean revoked) {
        super(JwtMetadata.JWT_METADATA);

        setId(id);
        setUserName(userName);
        setExpiryDate(expiryDate);
        setRevoked(revoked);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised JwtMetadataRecord
     */
    public JwtMetadataRecord(com.steeplesoft.simplesec.app.model.jooq.tables.pojos.JwtMetadata value) {
        super(JwtMetadata.JWT_METADATA);

        if (value != null) {
            setId(value.getId());
            setUserName(value.getUserName());
            setExpiryDate(value.getExpiryDate());
            setRevoked(value.getRevoked());
            resetChangedOnNotNull();
        }
    }
}
