/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.records;


import com.steeplesoft.simplesec.app.model.jooq.tables.PasswordRecovery;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordRecoveryRecord extends UpdatableRecordImpl<PasswordRecoveryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.password_recovery.id</code>.
     */
    public PasswordRecoveryRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.id</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.password_recovery.user_name</code>.
     */
    public PasswordRecoveryRecord setUserName(@Nullable String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.user_name</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.password_recovery.recovery_token</code>.
     */
    public PasswordRecoveryRecord setRecoveryToken(@Nullable String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.recovery_token</code>.
     */
    @Size(max = 6)
    @Nullable
    public String getRecoveryToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.password_recovery.expiry_date</code>.
     */
    public PasswordRecoveryRecord setExpiryDate(@Nullable Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.expiry_date</code>.
     */
    @Nullable
    public Long getExpiryDate() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PasswordRecoveryRecord
     */
    public PasswordRecoveryRecord() {
        super(PasswordRecovery.PASSWORD_RECOVERY);
    }

    /**
     * Create a detached, initialised PasswordRecoveryRecord
     */
    public PasswordRecoveryRecord(@Nullable Long id, @Nullable String userName, @Nullable String recoveryToken, @Nullable Long expiryDate) {
        super(PasswordRecovery.PASSWORD_RECOVERY);

        setId(id);
        setUserName(userName);
        setRecoveryToken(recoveryToken);
        setExpiryDate(expiryDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PasswordRecoveryRecord
     */
    public PasswordRecoveryRecord(com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery value) {
        super(PasswordRecovery.PASSWORD_RECOVERY);

        if (value != null) {
            setId(value.getId());
            setUserName(value.getUserName());
            setRecoveryToken(value.getRecoveryToken());
            setExpiryDate(value.getExpiryDate());
            resetChangedOnNotNull();
        }
    }
}
