/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.smij.app.model.jooq.tables.pojos;


import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JwtMetadata implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String userName;
    private OffsetDateTime expiryDate;
    private Boolean revoked;

    public JwtMetadata() {}

    public JwtMetadata(JwtMetadata value) {
        this.id = value.id;
        this.userName = value.userName;
        this.expiryDate = value.expiryDate;
        this.revoked = value.revoked;
    }

    public JwtMetadata(
        @Nonnull String id,
        @Nullable String userName,
        @Nullable OffsetDateTime expiryDate,
        @Nullable Boolean revoked
    ) {
        this.id = id;
        this.userName = userName;
        this.expiryDate = expiryDate;
        this.revoked = revoked;
    }

    /**
     * Getter for <code>public.jwt_metadata.id</code>.
     */
    @NotNull
    @Nonnull
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.jwt_metadata.id</code>.
     */
    public JwtMetadata setId(@Nonnull String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.user_name</code>.
     */
    @Size(max = 320)
    @Nullable
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.jwt_metadata.user_name</code>.
     */
    public JwtMetadata setUserName(@Nullable String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.expiry_date</code>.
     */
    @Nullable
    public OffsetDateTime getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Setter for <code>public.jwt_metadata.expiry_date</code>.
     */
    public JwtMetadata setExpiryDate(@Nullable OffsetDateTime expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }

    /**
     * Getter for <code>public.jwt_metadata.revoked</code>.
     */
    @Nullable
    public Boolean getRevoked() {
        return this.revoked;
    }

    /**
     * Setter for <code>public.jwt_metadata.revoked</code>.
     */
    public JwtMetadata setRevoked(@Nullable Boolean revoked) {
        this.revoked = revoked;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JwtMetadata other = (JwtMetadata) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.expiryDate == null) {
            if (other.expiryDate != null)
                return false;
        }
        else if (!this.expiryDate.equals(other.expiryDate))
            return false;
        if (this.revoked == null) {
            if (other.revoked != null)
                return false;
        }
        else if (!this.revoked.equals(other.revoked))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.expiryDate == null) ? 0 : this.expiryDate.hashCode());
        result = prime * result + ((this.revoked == null) ? 0 : this.revoked.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JwtMetadata (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(expiryDate);
        sb.append(", ").append(revoked);

        sb.append(")");
        return sb.toString();
    }
}
