/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.daos;


import com.steeplesoft.simplesec.app.model.jooq.tables.PasswordRecovery;
import com.steeplesoft.simplesec.app.model.jooq.tables.records.PasswordRecoveryRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordRecoveryDao extends DAOImpl<PasswordRecoveryRecord, com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery, Long> {

    /**
     * Create a new PasswordRecoveryDao without any configuration
     */
    public PasswordRecoveryDao() {
        super(PasswordRecovery.PASSWORD_RECOVERY, com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery.class);
    }

    /**
     * Create a new PasswordRecoveryDao with an attached configuration
     */
    public PasswordRecoveryDao(Configuration configuration) {
        super(PasswordRecovery.PASSWORD_RECOVERY, com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery.class, configuration);
    }

    @Override
    @Nonnull
    public Long getId(com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PasswordRecovery.PASSWORD_RECOVERY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchById(Long... values) {
        return fetch(PasswordRecovery.PASSWORD_RECOVERY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nullable
    public com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery fetchOneById(Long value) {
        return fetchOne(PasswordRecovery.PASSWORD_RECOVERY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    @Nonnull
    public Optional<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchOptionalById(Long value) {
        return fetchOptional(PasswordRecovery.PASSWORD_RECOVERY.ID, value);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PasswordRecovery.PASSWORD_RECOVERY.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchByUserName(String... values) {
        return fetch(PasswordRecovery.PASSWORD_RECOVERY.USER_NAME, values);
    }

    /**
     * Fetch records that have <code>recovery_token BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchRangeOfRecoveryToken(String lowerInclusive, String upperInclusive) {
        return fetchRange(PasswordRecovery.PASSWORD_RECOVERY.RECOVERY_TOKEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>recovery_token IN (values)</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchByRecoveryToken(String... values) {
        return fetch(PasswordRecovery.PASSWORD_RECOVERY.RECOVERY_TOKEN, values);
    }

    /**
     * Fetch records that have <code>expiry_date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchRangeOfExpiryDate(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PasswordRecovery.PASSWORD_RECOVERY.EXPIRY_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>expiry_date IN (values)</code>
     */
    @Nonnull
    public List<com.steeplesoft.simplesec.app.model.jooq.tables.pojos.PasswordRecovery> fetchByExpiryDate(Long... values) {
        return fetch(PasswordRecovery.PASSWORD_RECOVERY.EXPIRY_DATE, values);
    }
}
