/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.smij.app.model.jooq.tables.records;


import com.steeplesoft.smij.app.model.jooq.tables.FlywaySchemaHistory;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FlywaySchemaHistoryRecord extends UpdatableRecordImpl<FlywaySchemaHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledRank(@Nonnull Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_rank</code>.
     */
    @NotNull
    @Nonnull
    public Integer getInstalledRank() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.flyway_schema_history.version</code>.
     */
    public FlywaySchemaHistoryRecord setVersion(@Nullable String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.version</code>.
     */
    @Size(max = 50)
    @Nullable
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.flyway_schema_history.description</code>.
     */
    public FlywaySchemaHistoryRecord setDescription(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.description</code>.
     */
    @NotNull
    @Size(max = 200)
    @Nonnull
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.flyway_schema_history.type</code>.
     */
    public FlywaySchemaHistoryRecord setType(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.type</code>.
     */
    @NotNull
    @Size(max = 20)
    @Nonnull
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.flyway_schema_history.script</code>.
     */
    public FlywaySchemaHistoryRecord setScript(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.script</code>.
     */
    @NotNull
    @Size(max = 1000)
    @Nonnull
    public String getScript() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.flyway_schema_history.checksum</code>.
     */
    public FlywaySchemaHistoryRecord setChecksum(@Nullable Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.checksum</code>.
     */
    @Nullable
    public Integer getChecksum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.flyway_schema_history.installed_by</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledBy(@Nonnull String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_by</code>.
     */
    @NotNull
    @Size(max = 100)
    @Nonnull
    public String getInstalledBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.flyway_schema_history.installed_on</code>.
     */
    public FlywaySchemaHistoryRecord setInstalledOn(@Nullable LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.installed_on</code>.
     */
    @Nullable
    public LocalDateTime getInstalledOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.flyway_schema_history.execution_time</code>.
     */
    public FlywaySchemaHistoryRecord setExecutionTime(@Nonnull Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.execution_time</code>.
     */
    @NotNull
    @Nonnull
    public Integer getExecutionTime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.flyway_schema_history.success</code>.
     */
    public FlywaySchemaHistoryRecord setSuccess(@Nonnull Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.flyway_schema_history.success</code>.
     */
    @NotNull
    @Nonnull
    public Boolean getSuccess() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord() {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord(@Nonnull Integer installedRank, @Nullable String version, @Nonnull String description, @Nonnull String type, @Nonnull String script, @Nullable Integer checksum, @Nonnull String installedBy, @Nullable LocalDateTime installedOn, @Nonnull Integer executionTime, @Nonnull Boolean success) {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);

        setInstalledRank(installedRank);
        setVersion(version);
        setDescription(description);
        setType(type);
        setScript(script);
        setChecksum(checksum);
        setInstalledBy(installedBy);
        setInstalledOn(installedOn);
        setExecutionTime(executionTime);
        setSuccess(success);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FlywaySchemaHistoryRecord
     */
    public FlywaySchemaHistoryRecord(com.steeplesoft.smij.app.model.jooq.tables.pojos.FlywaySchemaHistory value) {
        super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);

        if (value != null) {
            setInstalledRank(value.getInstalledRank());
            setVersion(value.getVersion());
            setDescription(value.getDescription());
            setType(value.getType());
            setScript(value.getScript());
            setChecksum(value.getChecksum());
            setInstalledBy(value.getInstalledBy());
            setInstalledOn(value.getInstalledOn());
            setExecutionTime(value.getExecutionTime());
            setSuccess(value.getSuccess());
            resetChangedOnNotNull();
        }
    }
}
