/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.pojos;


import jakarta.annotation.Nullable;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PasswordRecovery implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String userName;
    private String recoveryToken;
    private OffsetDateTime expiryDate;

    public PasswordRecovery() {}

    public PasswordRecovery(PasswordRecovery value) {
        this.id = value.id;
        this.userName = value.userName;
        this.recoveryToken = value.recoveryToken;
        this.expiryDate = value.expiryDate;
    }

    public PasswordRecovery(
        @Nullable Long id,
        @Nullable String userName,
        @Nullable String recoveryToken,
        @Nullable OffsetDateTime expiryDate
    ) {
        this.id = id;
        this.userName = userName;
        this.recoveryToken = recoveryToken;
        this.expiryDate = expiryDate;
    }

    /**
     * Getter for <code>public.password_recovery.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.password_recovery.id</code>.
     */
    public PasswordRecovery setId(@Nullable Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.user_name</code>.
     */
    @Size(max = 320)
    @Nullable
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.password_recovery.user_name</code>.
     */
    public PasswordRecovery setUserName(@Nullable String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.recovery_token</code>.
     */
    @Size(max = 6)
    @Nullable
    public String getRecoveryToken() {
        return this.recoveryToken;
    }

    /**
     * Setter for <code>public.password_recovery.recovery_token</code>.
     */
    public PasswordRecovery setRecoveryToken(@Nullable String recoveryToken) {
        this.recoveryToken = recoveryToken;
        return this;
    }

    /**
     * Getter for <code>public.password_recovery.expiry_date</code>.
     */
    @Nullable
    public OffsetDateTime getExpiryDate() {
        return this.expiryDate;
    }

    /**
     * Setter for <code>public.password_recovery.expiry_date</code>.
     */
    public PasswordRecovery setExpiryDate(@Nullable OffsetDateTime expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PasswordRecovery other = (PasswordRecovery) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.recoveryToken == null) {
            if (other.recoveryToken != null)
                return false;
        }
        else if (!this.recoveryToken.equals(other.recoveryToken))
            return false;
        if (this.expiryDate == null) {
            if (other.expiryDate != null)
                return false;
        }
        else if (!this.expiryDate.equals(other.expiryDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.recoveryToken == null) ? 0 : this.recoveryToken.hashCode());
        result = prime * result + ((this.expiryDate == null) ? 0 : this.expiryDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PasswordRecovery (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(recoveryToken);
        sb.append(", ").append(expiryDate);

        sb.append(")");
        return sb.toString();
    }
}
