/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables.pojos;


import jakarta.annotation.Nullable;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tenantId;
    private Long id;
    private String userName;
    private String password;
    private String phoneNumber;
    private String address1;
    private String address2;
    private String city;
    private String state;
    private String zipCode;
    private String roles;
    private OffsetDateTime creationDate;
    private Integer failAttempts;
    private Long lockedUntil;

    public UserAccount() {}

    public UserAccount(UserAccount value) {
        this.tenantId = value.tenantId;
        this.id = value.id;
        this.userName = value.userName;
        this.password = value.password;
        this.phoneNumber = value.phoneNumber;
        this.address1 = value.address1;
        this.address2 = value.address2;
        this.city = value.city;
        this.state = value.state;
        this.zipCode = value.zipCode;
        this.roles = value.roles;
        this.creationDate = value.creationDate;
        this.failAttempts = value.failAttempts;
        this.lockedUntil = value.lockedUntil;
    }

    public UserAccount(
        @Nullable Long tenantId,
        @Nullable Long id,
        @Nullable String userName,
        @Nullable String password,
        @Nullable String phoneNumber,
        @Nullable String address1,
        @Nullable String address2,
        @Nullable String city,
        @Nullable String state,
        @Nullable String zipCode,
        @Nullable String roles,
        @Nullable OffsetDateTime creationDate,
        @Nullable Integer failAttempts,
        @Nullable Long lockedUntil
    ) {
        this.tenantId = tenantId;
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.phoneNumber = phoneNumber;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zipCode = zipCode;
        this.roles = roles;
        this.creationDate = creationDate;
        this.failAttempts = failAttempts;
        this.lockedUntil = lockedUntil;
    }

    /**
     * Getter for <code>public.user_account.tenant_id</code>.
     */
    @Nullable
    public Long getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.user_account.tenant_id</code>.
     */
    public UserAccount setTenantId(@Nullable Long tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Getter for <code>public.user_account.id</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_account.id</code>.
     */
    public UserAccount setId(@Nullable Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user_account.user_name</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.user_account.user_name</code>.
     */
    public UserAccount setUserName(@Nullable String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>public.user_account.password</code>.
     */
    @Size(max = 255)
    @Nullable
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.user_account.password</code>.
     */
    public UserAccount setPassword(@Nullable String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.user_account.phone_number</code>.
     */
    @Size(max = 50)
    @Nullable
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Setter for <code>public.user_account.phone_number</code>.
     */
    public UserAccount setPhoneNumber(@Nullable String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    /**
     * Getter for <code>public.user_account.address1</code>.
     */
    @Size(max = 100)
    @Nullable
    public String getAddress1() {
        return this.address1;
    }

    /**
     * Setter for <code>public.user_account.address1</code>.
     */
    public UserAccount setAddress1(@Nullable String address1) {
        this.address1 = address1;
        return this;
    }

    /**
     * Getter for <code>public.user_account.address2</code>.
     */
    @Size(max = 100)
    @Nullable
    public String getAddress2() {
        return this.address2;
    }

    /**
     * Setter for <code>public.user_account.address2</code>.
     */
    public UserAccount setAddress2(@Nullable String address2) {
        this.address2 = address2;
        return this;
    }

    /**
     * Getter for <code>public.user_account.city</code>.
     */
    @Size(max = 100)
    @Nullable
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.user_account.city</code>.
     */
    public UserAccount setCity(@Nullable String city) {
        this.city = city;
        return this;
    }

    /**
     * Getter for <code>public.user_account.state</code>.
     */
    @Size(max = 10)
    @Nullable
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.user_account.state</code>.
     */
    public UserAccount setState(@Nullable String state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>public.user_account.zip_code</code>.
     */
    @Size(max = 10)
    @Nullable
    public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Setter for <code>public.user_account.zip_code</code>.
     */
    public UserAccount setZipCode(@Nullable String zipCode) {
        this.zipCode = zipCode;
        return this;
    }

    /**
     * Getter for <code>public.user_account.roles</code>.
     */
    @Size(max = 1000)
    @Nullable
    public String getRoles() {
        return this.roles;
    }

    /**
     * Setter for <code>public.user_account.roles</code>.
     */
    public UserAccount setRoles(@Nullable String roles) {
        this.roles = roles;
        return this;
    }

    /**
     * Getter for <code>public.user_account.creation_date</code>.
     */
    @Nullable
    public OffsetDateTime getCreationDate() {
        return this.creationDate;
    }

    /**
     * Setter for <code>public.user_account.creation_date</code>.
     */
    public UserAccount setCreationDate(@Nullable OffsetDateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Getter for <code>public.user_account.fail_attempts</code>.
     */
    @Nullable
    public Integer getFailAttempts() {
        return this.failAttempts;
    }

    /**
     * Setter for <code>public.user_account.fail_attempts</code>.
     */
    public UserAccount setFailAttempts(@Nullable Integer failAttempts) {
        this.failAttempts = failAttempts;
        return this;
    }

    /**
     * Getter for <code>public.user_account.locked_until</code>.
     */
    @Nullable
    public Long getLockedUntil() {
        return this.lockedUntil;
    }

    /**
     * Setter for <code>public.user_account.locked_until</code>.
     */
    public UserAccount setLockedUntil(@Nullable Long lockedUntil) {
        this.lockedUntil = lockedUntil;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAccount other = (UserAccount) obj;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        }
        else if (!this.tenantId.equals(other.tenantId))
            return false;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!this.userName.equals(other.userName))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.phoneNumber == null) {
            if (other.phoneNumber != null)
                return false;
        }
        else if (!this.phoneNumber.equals(other.phoneNumber))
            return false;
        if (this.address1 == null) {
            if (other.address1 != null)
                return false;
        }
        else if (!this.address1.equals(other.address1))
            return false;
        if (this.address2 == null) {
            if (other.address2 != null)
                return false;
        }
        else if (!this.address2.equals(other.address2))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.zipCode == null) {
            if (other.zipCode != null)
                return false;
        }
        else if (!this.zipCode.equals(other.zipCode))
            return false;
        if (this.roles == null) {
            if (other.roles != null)
                return false;
        }
        else if (!this.roles.equals(other.roles))
            return false;
        if (this.creationDate == null) {
            if (other.creationDate != null)
                return false;
        }
        else if (!this.creationDate.equals(other.creationDate))
            return false;
        if (this.failAttempts == null) {
            if (other.failAttempts != null)
                return false;
        }
        else if (!this.failAttempts.equals(other.failAttempts))
            return false;
        if (this.lockedUntil == null) {
            if (other.lockedUntil != null)
                return false;
        }
        else if (!this.lockedUntil.equals(other.lockedUntil))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.phoneNumber == null) ? 0 : this.phoneNumber.hashCode());
        result = prime * result + ((this.address1 == null) ? 0 : this.address1.hashCode());
        result = prime * result + ((this.address2 == null) ? 0 : this.address2.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.zipCode == null) ? 0 : this.zipCode.hashCode());
        result = prime * result + ((this.roles == null) ? 0 : this.roles.hashCode());
        result = prime * result + ((this.creationDate == null) ? 0 : this.creationDate.hashCode());
        result = prime * result + ((this.failAttempts == null) ? 0 : this.failAttempts.hashCode());
        result = prime * result + ((this.lockedUntil == null) ? 0 : this.lockedUntil.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAccount (");

        sb.append(tenantId);
        sb.append(", ").append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(address1);
        sb.append(", ").append(address2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(zipCode);
        sb.append(", ").append(roles);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(failAttempts);
        sb.append(", ").append(lockedUntil);

        sb.append(")");
        return sb.toString();
    }
}
