/*
 * This file is generated by jOOQ.
 */
package com.steeplesoft.simplesec.app.model.jooq.tables;


import com.steeplesoft.simplesec.app.model.jooq.Keys;
import com.steeplesoft.simplesec.app.model.jooq.Public;
import com.steeplesoft.simplesec.app.model.jooq.tables.records.JwtMetadataRecord;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JwtMetadata extends TableImpl<JwtMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.jwt_metadata</code>
     */
    public static final JwtMetadata JWT_METADATA = new JwtMetadata();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<JwtMetadataRecord> getRecordType() {
        return JwtMetadataRecord.class;
    }

    /**
     * The column <code>public.jwt_metadata.id</code>.
     */
    public final TableField<JwtMetadataRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.jwt_metadata.user_name</code>.
     */
    public final TableField<JwtMetadataRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.jwt_metadata.expiry_date</code>.
     */
    public final TableField<JwtMetadataRecord, Long> EXPIRY_DATE = createField(DSL.name("expiry_date"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.jwt_metadata.revoked</code>.
     */
    public final TableField<JwtMetadataRecord, Boolean> REVOKED = createField(DSL.name("revoked"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private JwtMetadata(Name alias, Table<JwtMetadataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private JwtMetadata(Name alias, Table<JwtMetadataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.jwt_metadata</code> table reference
     */
    public JwtMetadata(String alias) {
        this(DSL.name(alias), JWT_METADATA);
    }

    /**
     * Create an aliased <code>public.jwt_metadata</code> table reference
     */
    public JwtMetadata(Name alias) {
        this(alias, JWT_METADATA);
    }

    /**
     * Create a <code>public.jwt_metadata</code> table reference
     */
    public JwtMetadata() {
        this(DSL.name("jwt_metadata"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<JwtMetadataRecord> getPrimaryKey() {
        return Keys.JWT_METADATA_PKEY;
    }

    @Override
    @Nonnull
    public JwtMetadata as(String alias) {
        return new JwtMetadata(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public JwtMetadata as(Name alias) {
        return new JwtMetadata(alias, this);
    }

    @Override
    @Nonnull
    public JwtMetadata as(Table<?> alias) {
        return new JwtMetadata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public JwtMetadata rename(String name) {
        return new JwtMetadata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public JwtMetadata rename(Name name) {
        return new JwtMetadata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public JwtMetadata rename(Table<?> name) {
        return new JwtMetadata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata where(Condition condition) {
        return new JwtMetadata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public JwtMetadata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public JwtMetadata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public JwtMetadata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public JwtMetadata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public JwtMetadata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
