name: Build and deploy

on:
  workflow_dispatch:
    branches:
      - '**'
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'maven'

    - name: Restore cached Maven packages
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.m2
          ~/.local/share/containers
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}

    - name: Build and test
      run: mvn -B -fae clean package -Dgithub=true

    - name: Cache Maven packages
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.m2
          ~/.local/share/containers
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-build-artifacts
        path: '**/target/*.jar'
        retention-days: 5
        if-no-files-found: error
